# Minimal but informative prompt
format = """$directory$git_branch$git_status$nodejs$python$ruby$golang$rust$cmd_duration$line_break$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
format = " [$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 3_000
format = " [$duration]($style)"
style = "bold yellow"

[nodejs]
format = " [$symbol$version]($style)"
symbol = " "

[python]
format = " [$symbol$version]($style)"
symbol = " "

[ruby]
format = " [$symbol$version]($style)"
symbol = " "

[golang]
format = " [$symbol$version]($style)"
symbol = " "

[rust]
format = " [$symbol$version]($style)"
symbol = " "
